apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: weshare-poc
  region: eu-west-3

managedNodeGroups:
  - name: weshare-ng
    labels: { role: workers }
    instanceType: t3.medium
    desiredCapacity: 2
    volumeSize: 10
    privateNetworking: true